CREATE DATABASE IF NOT EXISTS my_database;
CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT ALL PRIVILEGES ON my_database.* TO '${MYSQL_USER}'@'%';
FLUSH PRIVILEGES;
